# Generated by Django 2.2.2 on 2019-11-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=40)),
            ],
        ),
    ]
