# Generated by Django 2.2.2 on 2019-11-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMassIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BMI', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defg', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(max_length=50, null=True)),
                ('height', models.IntegerField(max_length=50, null=True)),
                ('weight', models.IntegerField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('activity', models.CharField(max_length=50, null=True)),
                ('diabetes', models.CharField(max_length=50, null=True)),
                ('heart', models.CharField(max_length=50, null=True)),
                ('kidney', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
