# Generated by Django 2.2.2 on 2019-11-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_bodymassindex_calories_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
