# Generated by Django 2.2.2 on 2019-11-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_auto_20191104_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='heart',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='kidney',
        ),
    ]
